[monitors]
[monitors.work]
[monitors.work.left]
name = "Dell Inc. DELL U3219Q F2XWXV2"
mode = "3840x2160@60Hz"
position = "0x0"
scale = "1.25"
# scale = "1.27525528811"

[monitors.work.center]
name = "Acer Technologies XV340CK P T5Y000013E00"
mode = "3440x1440@144Hz"
position = "1694x786"
scale = "1"

[monitors.work.right]
name = "Dell Inc. DELL U2515H 9X2VY6A80A8L"
mode = "2560x1440@60Hz"
position = "5134x226"
scale = "1"

[monitors.work.laptop]
name = "LG Display 0x0662"
mode = "1920x1080@60Hz"
position = "2454x2226"
scale = "1"

[monitors.home]
[monitors.home.left]
name = "Dell Inc. DELL U2515H 9X2VY4B101CL"
mode = "3840x2160@60Hz"
position = "0x30"
scale = "1"

[monitors.home.center]
name = "Acer Technologies XF270HU T78EE0048521"
mode = "2560x1440@144Hz"
position = "1440x570"
scale = "1"

[monitors.home.right]
name = "Dell Inc. DELL U2515H 9X2VY4B101BL"
mode = "2560x1440@60Hz"
position = "4000x0"
scale = "1"

[monitors.home.tv]
name = "LG Electronics LG TV 0x01010101"
mode = "3840x2160@120Hz"
position = "6560x0"
scale = "1.5"

[monitors.home.laptop]
name = "LG Display 0x0662"
mode = "1920x1080@60Hz"
position = "3181x1905"
scale = "1"
