[workspaces]
left = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
center = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112]
right = [201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212]
laptop = [301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312]

[workspaces.associations]
mail = [1, 111]
media = [2, 112]
messages = [3, 109]
chats = [4, 110]
work_comm = [5, 105]
browser = [301, 101]

[monitors]
[monitors.work]
screen_timeout = 3600
lock_timeout = 300
default_profile = "desk"

[monitors.work.profile_settings.desk]
label = "Desk"

[monitors.work.profile_settings.desk_laptop]
label = "Desk + Laptop"

[monitors.work.left]
name = "Dell Inc. DELL U3219Q F2XWXV2"
workspaces = "left"
shikane_search = ["m=DELL U3219Q", "s=F2XWXV2", "v=Dell Inc."]
bar_position = "bottom"
mode = "3840x2160@60Hz"
position = "0x0"
scale = "1.25"
transform = 1
background = "~/.config/wallpapers/dark/2160x3840/ren-ran-HG5QX-GXV5A-unsplash.jpg"
profiles = ["desk", "desk_laptop"]

[monitors.work.center]
name = "Dell Inc. DELL U4025QW 1WM5M04"
workspaces = "center"
shikane_search = ["m=DELL U4025QW", "s=1WM5M04", "v=Dell Inc."]
bar_position = "bottom"
mode = "5120x2160@120Hz"
position = "1728x642"
scale = "1.25"
transform = 0
background = "~/.config/wallpapers/dark/2560x1440/jaime-lannister.jpg"
profiles = ["desk", "desk_laptop"]

[monitors.work.right]
name = "Dell Inc. DELL U2515H 9X2VY6A80A8L"
workspaces = "right"
shikane_search = ["m=DELL U2515H", "s=9X2VY6A80A8L", "v=Dell Inc."]
bar_position = "bottom"
mode = "2560x1440@60Hz"
position = "5824x150"
scale = "1"
transform = 3
background = "~/.config/wallpapers/dark/2160x3840/eberhard-grossgasteiger-7ZxpAr4cZ-U-unsplash.jpg"
profiles = ["desk", "desk_laptop"]

[monitors.work.laptop]
name = "Lenovo Group Limited 0x4149"
workspaces = "laptop"
shikane_search = ["m=0x4149", "v=Lenovo Group Limited"]
bar_position = "top"
mode = "2880x1800@90Hz"
position = "3776x2370"
scale = "1.8"
background = "~/.config/wallpapers/dark/2560x1440/jaime-lannister.jpg"
has_lid = true
profiles = ["desk_laptop"]

[monitors.home]
screen_timeout = 300
lock_timeout = 600
default_profile = "desk"

[monitors.home.profile_settings.desk]
label = "Desk"
audio_sink = "alsa_output.usb-FiiO_DigiHug_USB_Audio-01.analog-stereo"
audio_source = "alsa_input.usb-BLUE_MICROPHONE_Blue_Snowball_201305-00.analog-stereo"

[monitors.home.profile_settings.desk_living_room]
label = "Desk + Living Room"
audio_sink = "raop_sink.Sonos-38420BD3AE96.local.10.10.10.31.7000"
audio_source = "alsa_input.usb-BLUE_MICROPHONE_Blue_Snowball_201305-00.analog-stereo"

[monitors.home.profile_settings.living_room]
label = "Living Room"
audio_sink = "raop_sink.Sonos-38420BD3AE96.local.10.10.10.31.7000"
audio_source = "alsa_input.usb-BLUE_MICROPHONE_Blue_Snowball_201305-00.analog-stereo"

[monitors.home.profile_settings.laptop]
label = "Laptop"

[monitors.home.left]
name = "Lenovo Group Limited Y32p-30 U1HMF6PT"
workspaces = "left"
shikane_search = ["m=Y32p-30", "s=U1HMF6PT", "v=Lenovo Group Limited"]
serial_number = "U1HMF6PT"
bar_position = "bottom"
mode = "3840x2160@143.999Hz"
position = "0x0"
scale = "1.25"
transform = 1
background = "~/.config/wallpapers/dark/2160x3840/ren-ran-HG5QX-GXV5A-unsplash.jpg"
profiles = ["desk", "desk_living_room"]

[monitors.home.center]
name = "Dell Inc. AW3225QF GZ00YZ3"
workspaces = "center"
shikane_search = ["m=AW3225QF", "s=GZ00YZ3", "v=Dell Inc."]
serial_number = "GZ00YZ3"
bar_position = "bottom"
mode = "3840x2160@240Hz"
position = "1728x865"
scale = "1.25"
transform = 0
vrr = 0
color = "#000000"
profiles = ["desk", "desk_living_room"]

[monitors.home.right]
name = "Lenovo Group Limited Y32p-30 U1HMF6PN"
workspaces = "right"
shikane_search = ["m=Y32p-30", "s=U1HMF6PN", "v=Lenovo Group Limited"]
serial_number = "U1HMF6PN"
bar_position = "bottom"
mode = "3840x2160@120Hz"
position = "4800x0"
scale = "1.25"
transform = 3
background = "~/.config/wallpapers/dark/2160x3840/eberhard-grossgasteiger-7ZxpAr4cZ-U-unsplash.jpg"
profiles = ["desk", "desk_living_room"]

[monitors.home.tv]
name = "LG Electronics LG TV 0x01010101"
workspaces = "laptop"
shikane_search = ["m=LG TV", "s=0x01010101", "v=LG Electronics"]
serial_number = "0x01010101"
bar_position = "bottom"
mode = "3840x2160@60Hz"
position = "1984x-575"
scale = "2"
profiles = ["living_room", "desk_living_room"]

[monitors.home.laptop]
name = "LG Display 0x07C6"
workspaces = "laptop"
shikane_search = ["m=0x07C6", "v=LG Display"]
serial_number = ""
bar_position = "top"
mode = "2880x1800@120"
position = "0x0"
scale = "1.67"
vrr = 1
profiles = ["laptop"]

[themes.rubecula]
name = "rubecula"
background = "#1c1c1c"
transparency = 0.8
foreground = "#e5e5e5"
cursor = "#F8F8F0"
cursor_text_color = "#E5E5E5"
url_color = "#e5e5e5"
selection_background = "#CCC47A"
color0 = "#797c6a"
color1 = "#e52e71"
color2 = "#9ccc3d"
color3 = "#ccc47a"
color4 = "#6d8fd9"
color5 = "#a082d9"
color6 = "#6cc7d9"
color7 = "#e5e5e5"
color8 = "#797c6a"
color9 = "#e52e71"
color10 = "#9ccc3d"
color11 = "#ccc47a"
color12 = "#6d8fd9"
color13 = "#a082d9"
color14 = "#6cc7d9"
color15 = "#e5e5e5"

[themes.rubecula_dawn]
name = "rubecula-dawn"
type = "light"

black = "#141414"
blackGray = "#1C1C1C"
darkerGray = "#242424"
darkGray = "#404040"
gray = "#6E6E6E"
lightGray = "#CECECE"
lighterGray = "#D6D6D6"
whiteGray = "#DEDEDE"
white = "#E5E5E5"
realwhite = "#FFFFFF"

blue = "#5caeef"
lightBlue = "#ABB2C0"

yellow = "#7E7630"

pink = "#E52E71"
lightPink = "#DB6165"

green = "#618122"
lightGreen = "#97C26C"

cyan = "#24798A"
lightCyan = "#4FB1BC"

orange = "#D9882B"
lightOrange = "#DFB976"

purple = "#673ABB"
lightPurple = "#C172D9"

transparent = "#FFFFFF00"

darkBackground = "#E5E5E5"
background = "#FFFFFF"
lightBackground = "#DEDEDE"
highlightBackground = "#14141415"
activeBackground = "#14141425"
selectionBackground = "#7E763040"
inactiveSelectionBackground = "#7E763030"
inactiveBackground = "#7E763020"

border = "#CECECE"

brightForeground = "#141414"
foreground = "#404040"
inactiveForeground = "#6E6E6E"

transparency = 1
cursor = "#141414"
cursor_text_color = "#FFFFFF"
url_color = "#24798A"
selection_background = "#cbc7ad"
color0 = "#6E6E6E"
color1 = "#E52E71"
color2 = "#618122"
color3 = "#7E7630"
color4 = "#5caeef"
color5 = "#673ABB"
color6 = "#24798A"
color7 = "#404040"
color8 = "#6E6E6E"
color9 = "#E52E71"
color10 = "#618122"
color11 = "#7E7630"
color12 = "#5caeef"
color13 = "#673ABB"
color14 = "#24798A"
color15 = "#141414"
