
# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = compose:ralt
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        scroll_factor = 0.50
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

device {
    name = ven_2c2f:00-2c2f:0034-touchpad
    sensitivity = 0.25
    accel_profile = adaptive
    #accel_profile = custom 1.0 0.0 1.0
    scroll_points = 0.20 0.0 0.25 0.40 0.65 1.00 1.00 1.45 1.30 2.00
}

gestures {
    workspace_swipe_distance = 300
    workspace_swipe_invert = true
    workspace_swipe_min_speed_to_force = 5
    workspace_swipe_cancel_ratio = 0.35
    workspace_swipe_direction_lock = false
    workspace_swipe_direction_lock_threshold = 12
    workspace_swipe_forever = false
    workspace_swipe_create_new = false
}

gesture = 3, horizontal, workspace, scale:1.0

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
#device:epic-mouse-v1 {
#    sensitivity = -0.5
#}

# TODO Find a way to enable compose key
