general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}

decoration {
    rounding = 0

    blur {
        enabled = false
    }
}

animations {
    enabled = yes

    bezier = overshot, 0.05, 0.9, 0.1, 1.05
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = smoothIn, 0.25, 1, 0.5, 1
    bezier = macos_ws, 0.22, 0.9, 0.12, 1.0

    animation = windows, 1, 2, overshot, gnomed
    animation = windowsOut, 1, 2, smoothOut, gnomed
    animation = layers, 1, 3, default, popin
    #animation = layersIn, 1, 2, default, popin
    #animation = layersOut, 1, 2, smoothOut, popin
    animation = windowsMove, 1, 2, default
    animation = border, 1, 2, default
    animation = fade, 1, 2, smoothIn
    animation = fadeLayersIn, 0
    animation = fadeLayersOut, 1, 2, smoothOut
    animation = fadeDim, 1, 2, smoothIn
    animation = workspaces, 1, 5, macos_ws, slide

    #animation = notifications, 1, 5, overshot, slide
}

layerrule {
    name = notifications
    match:namespace = notifications
    animation = slide right
}

layerrule {
    name = wayshot
    match:namespace = wayshot
    no_anim = on
}

layerrule {
    name = wayshot-selection
    match:namespace = osk
    no_anim = on
}

layerrule {
    name = grim-selection
    match:namespace = selection
    no_anim = on
}

layerrule {
    name = hyprpicker-hyprshot
    match:namespace = hyprpicker
    no_anim = on
}
layerrule {
     name = bar-top
     match:namespace = ^ags-bar-top.*
     animation = slide top
}


layerrule {
     name = bar-bottom
     match:namespace = ^ags-bar-bottom.*
     animation = slide bottom
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  key_press_enables_dpms = true
  background_color = rgb(000000)

  middle_click_paste = false
}
