#!/usr/bin/env zsh

set -e

source ~/.bin/utils.zsh

function check_cache() {
    if is_fedora; then
        amount=`dnf check-update --cacheonly --quiet --disablerepo="cpe-yum*" | wc -l`
    else
        amount=`paru -Qu | wc -l`
    fi

    # Return as fast as possible, then update the repos and update.
    if is_wayland; then
        waybar-json "$amount"
    else
        echo "$amount"
    fi
}

function check_live() {
    if is_fedora; then
        amount=`dnf check-update --refresh --quiet --disablerepo="cpe-yum*" | wc -l || echo "-1"`
    else
        amount=`paru -Syy &> /dev/null; paru -Qu | wc -l || echo "-1"`
    fi

    if [[ "$amount" == "-1" ]]; then
        return
    fi

    if is_wayland; then
        waybar-json "$amount"
    else
        echo "$amount"
    fi
}

function update_package_manager() {
    if is_fedora; then
        sudo dnf upgrade --refresh --assumeyes
    else
        paru -Syu --noconfirm
    fi
}

function update_flatpak() {
    flatpak remove --unused --assumeyes && flatpak update --assumeyes
}

function update_snap() {
    sudo snap refresh
}

case "$1" in
    check)
        check_cache
        check_live
        ;;
    monitor)
        check_cache
        while true; do
            check_live
            sleep 60
        done
        ;;
    update)
        case "$2" in
            --kitty)
                kitty @ goto-layout vertical
                kitty @ launch --title "Flatpak update" --no-response --dont-take-focus --type window -- updates update --flatpak
                kitty @ launch --title "Snap update" --no-response --dont-take-focus --type window -- updates update --snap
                kitty @ launch --title "Package manager update" --no-response --dont-take-focus --type window -- updates update --package-manager
                ;;
            --package-manager)
                update_package_manager
                ;;
            --flatpak)
                update_flatpak
                ;;
            --snap)
                update_snap
                ;;
            *)
                # If desktop environment is running.
                if [[ -n "$DESKTOP_SESSION" ]]; then
                    kitty @ launch --title "Starting update" --no-response --dont-take-focus --type os-window -- updates update --kitty
                else
                    update_package_manager
                    update_flatpak
                    update_snap
                fi
        esac
        ;;
    *)
        echo "Usage: $0 {check|monitor|update}"
        exit 2
esac

exit 0
