#!/usr/bin/env zsh

set -eo pipefail

if type "wayshot" >/dev/null; then
    wayshot -g --clipboard
elif type "hyprshot" >/dev/null; then
  hyprshot --freeze --clipboard-only --silent  --mode region
else
    grim -g "$(slurp)" - | wl-copy
fi

notify-send "📸 Screenshot saved to clipboard!" "Press Super+Shift+C to upload." --category transfer.complete
