#!/usr/bin/env zsh

port=5555
host=192.168.1.99
wifiConnected=$(adb devices | grep "$host:$port\tdevice")
if [ -n "$wifiConnected" ]; then
    echo "Your device is already connected via port $port."
else
    wifiStartConnectionCommand="adb connect $host | grep 'connected to $host:$port'"
    wifiStartConnection=$(eval $wifiStartConnectionCommand)
    if [ -n "$wifiStartConnection" ]; then
        echo "Sucessfully connected to your device via port $port."
    else
        usbConnected=`adb devices | grep '\tdevice'`
        if [ -n "$usbConnected" ]; then
            portopen=`adb tcpip $port > /dev/null`
            wifiStartConnection=-$(eval $wifiStartConnectionCommand)
            if [ -n "$wifiStartConnection" ]; then
                echo "Successfully connected to your device after opening port $port."
            else
                echo "Could not connect to your device even after opening port $port."
            fi
        else
            echo "Please connect your device so I can open port $port."
        fi
    fi
fi
