#!/usr/bin/env zsh

set -e

# This needs to be able to run from root as well.
SCRIPT_DIR=`dirname "$0"`
source "$SCRIPT_DIR/utils.zsh"

function is_timer_active() {
    if systemctl is-active --quiet create-backup.timer; then
        true
    else
        false
    fi
}

function is_service_active() {
    if systemctl is-active --quiet create-backup.service; then
        true
    else
        false
    fi
}

function is_service_failed() {
    if systemctl is-failed --quiet create-backup.service; then
        true
    else
        false
    fi
}

function is_timer_waiting() {
    timer_status=`systemctl status --quiet create-backup.timer`
    if  [[ $timer_status == *"Active: active (waiting)"* ]]; then
        true
    else
        false
    fi
}

function status() {
    if is_timer_active; then
        if is_service_active; then
            waybar-json "\uf382" "Backing up..." running
        else
            if is_service_failed; then
                waybar-json "\uf7e4" "Backup has failed, click to try again." failed
            else
                waybar-json "\uf0c2" "Backup timer is waiting for the next backup. Click to start now." waiting
            fi
        fi
    else
        waybar-json "\uf740" "Backup not active." inactive
    fi
}

case "$1" in
    status)
        status
        ;;
    update)
        pkill -RTMIN+8 waybar
        ;;
    start)
        if ! is_timer_active; then
            sudo systemctl start create-backup.timer
        fi
        sudo systemctl start create-backup.service
        ;;
    *)
        echo "Usage: $0 {status|update|activate}"
        exit 1
        ;;
esac
