#!/usr/bin/env zsh

if [ $# -ge 1 ]; then
    typeset -A sizes
    sizes=( 260 462 520 924 752 1346 )
    directory="output"
    if [ ! -e "$1" ]; then
        echo "The file \"$1\" does not exist."
    else
        if [ ! -d "$directory" ]; then
            mkdir $directory
            echo "Created directory \"$directory\" for converted files."
        else
            rm -rf $directory/*
            echo "Removed directory files from \"$directory\" before converting files."
        fi
        for width in "${(@k)sizes}"; do
            height="$sizes[$width]"
            for fps in 30 60; do
                outputFilename="$directory"/"$width"x"$height"-"$fps"
                ffmpeg -i "$1" -y -r $fps -vf scale="$width":"$height" -pix_fmt yuv420p -movflags faststart -vcodec libx264 -vpre slow -vpre baseline -an "${outputFilename}.mp4"
                ffmpeg -i "$1" -y -r $fps -vf scale="$width":"$height" -pix_fmt yuv420p -movflags faststart -vcodec libvpx -f webm -an "${outputFilename}.webm"
                ffmpeg -i "$1" -y -r $fps -vf scale="$width":"$height" -pix_fmt yuv420p -movflags faststart -vcodec libtheora -an "${outputFilename}.ogv"
            done
        done
    fi
else
    echo "Please enter a filename."
fi
