#!/usr/bin/bash
set -e

source /home/andreas/.config/.secrets

export BORG_REPO=/mnt/server/storage/Backups
export BORG_BASE_DIR=/home/andreas

echo "Creating backup..."
/usr/bin/borg create					                        \
    ::'{hostname}-{now:%Y-%m-%dT%H:%M:%S}'                      \
    /home/andreas                                               \
    /etc                                                        \
    /var                                                        \
    /usr/local                                                  \
    --compression auto,lzma                                     \
    --exclude-caches                                            \
    --show-rc                                                   \
    --list                                                      \
    --filter AME                                                \
    --one-file-system                                           \
    --debug						                                \
    --stats						                                \
    --exclude '/mnt'                                            \
    --exclude '/home/*/.cache'                                  \
    --exclude '/tmp'                                            \
    --exclude '/var/cache'                                      \
    --exclude '/var/log'                                        \
    --exclude '/var/tmp'                                        \
    --exclude '/var/lock'                                       \
    --exclude '/var/run'                                        \
    --exclude '/var/spool'                                      \
    --exclude '*.pyc'                                           \
    --exclude '*.log'                                           \
    --exclude 'Movies'                                          \
    --exclude '.gradle'                                         \
    --exclude '.local'                                          \
    --exclude '.pyenv'                                          \
    --exclude '.rbenv'                                          \
    --exclude '.npm-global'                                     \
    --exclude 'Downloads'                                       \
    --exclude '.npm/_cacache'                                   \
    --exclude 'node_modules'                                    \
    --exclude '__pycache__'                                     \
    --exclude '*Cache*'                                         \
    --exclude '*cache*'                                         \
    --exclude '*logs*'                                          \
    --exclude '.AndroidStudio*'                                 \
    --exclude '.IntelliJ*'                                      \
    --exclude '.CLion*'

echo "Pruning backup..."
/usr/bin/borg prune \
    -v \
    --list \
    --prefix '{hostname}-' \
    --keep-daily=2 \
    --keep-weekly=4 \
    --keep-monthly=6
