#!/usr/bin/env zsh

source ~/.secrets

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch polybar
# Nouveau
# MONITOR=HDMI-1 polybar landscape &
# MONITOR=DP-3 polybar portrait &

# Nvidia proprietary drivers
MONITOR=DisplayPort-0 polybar center &
MONITOR=DisplayPort-4 polybar right &
MONITOR=DisplayPort-3 polybar left &
