#!/usr/bin/env zsh

MAC_ADDRESS="04:52:C7:7A:D9:C8"

function bluetooth() {
    cmd="$1"
    echo "$cmd"
    result=`echo -e "$cmd $MAC_ADDRESS" | bluetoothctl 2>/dev/null`
    echo $result
}

function is_connected() {
    connected=`bluetooth info | grep "Connected:"`
    if [[ $connected == *"yes"* ]]; then
        true
    else
        false
    fi
}

case "$1" in
    connect)
        echo "Connecting..."
        bluetooth connect
        ;;
    disconnect)
        echo "Disconnecting..."
        bluetooth disconnect
        ;;
    toggle)
        if is_connected; then
            $0 disconnect
        else
            $0 connect
        fi
        ;;
    battery)
        based-connect --battery-level $MAC_ADDRESS
        ;;
    noise-cancellation)
        based-connect --noise-cancelling $2 $MAC_ADDRESS
        ;;
    status)
        if is_connected; then
            echo "%{F#CECECE}%{F-}"
        else
            echo "%{F#6E6E6E}%{F-}"
        fi
        ;;
    *)
        echo "Usage: $0 {status|connect|disconnect|toggle}"
        exit 1
        ;;
esac
