#!/usr/bin/env zsh

file_location_left=/tmp/lockscreen_left.png
file_location_center=/tmp/lockscreen_center.png
file_location_right=/tmp/lockscreen_right.png

parallel --verbose --link 'grim -o {1} - | convert - -encoding png -scale 10% -scale 1000% {2}' ::: DP-4 DP-1 DP-5 ::: $file_location_left $file_location_center $file_location_right

spotify_status=`spotifycl status`
spotifycl pause &

# Pause notifications
killall -USR1 dunst

if [[ $# -eq 1 ]] ; then
    sudo systemctl $1
fi

# Lock
swaylock \
    --image "DP-4:$file_location_left" \
    --image "DP-1:$file_location_center" \
    --image "DP-5:$file_location_right" \
    --font="Roboto Regular"

# Resume notifications
killall -USR2 dunst
if [[ "$spotify_status" == "playing" ]]; then
    spotifycl play &
fi

parallel --link rm {} ::: $file_location_left $file_location_center $file_location_right
