#!/usr/bin/env bash
#
file_location=/tmp/lockscreen.png
scrot $file_location
convert $file_location -scale 10% -scale 1000% $file_location
[[ -f $1 ]] && convert $file_location $1 -gravity center -composite -matte $file_location

# ratio for rectangle to be drawn for time background on lockscreen
# rectangles=" "
# SR=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]*x[0-9][0-9]*[^ ]*')
# for RES in $SR; do
#   SRA=(${RES//[x+]/ })
#   CX=$((${SRA[2]} + 25))
#   CY=$((${SRA[1]} - 110))
#   rectangles+="roundRectangle $CX,$CY $((CX+300)),$((CY-80)) 1,1"
# done
# convert "$file_location" -draw "fill black fill-opacity 0.4 $rectangles" "$file_location"

player_status=`playerctl status`
playerctl pause &
# pause notifications
killall -USR1 dunst

if [[ $# -eq 1 ]] ; then
    sudo systemctl $1
fi

# Lock
# i3lock -nei $file_location
# betterlock -l dimblur
i3lock \
    -n -i "$file_location" \
    --time-font="Roboto Regular" \
    --timesize="32" \
    --timestr="%H:%M" \
    --timepos="85:h-70" \
    --datepos="95:h-45" \
    --date-font="Roboto Regular" \
    --datesize="14" \
    --clock --datestr "Enter Password" \
    --insidecolor="00000000" --ringcolor="ffffffff" --line-uses-inside \
    --keyhlcolor="E52E71FF" --bshlcolor="E52E71FF" --separatorcolor="00000000" \
    --insidevercolor="CCC47AFF" --insidewrongcolor="E52E71FF" \
    --ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="x+280:h-70" \
    --radius=20 --ring-width=3 --veriftext="" --wrongtext="" \
    --layoutcolor="ffffffff" --timecolor="ffffffff" --datecolor="ffffffff"

# rm $file_location &
# resume notifications
killall -USR2 dunst
if [[ "$player_status" == "Playing" ]]; then
    playerctl play &
fi
