#!/usr/bin/env zsh

setopt sh_word_split
output=`pulseaudio-ctl full-status`
words=($output)

level=${words[1]}
sink_mute=${words[2]}
source_mute=${words[3]}

volume_min=""
volume_avg=""
volume_max=""
volume_mtd=""

if [[ "$sink_mute" == "yes" ]]; then
    echo "%{F#6E6E6E}$volume_mtd%{F-} $level%"
elif [[ level -eq 0 ]]; then
    echo "%{F#6E6E6E}$volume_min%{F-} $level%"
elif [[ level -le 75 ]]; then
    echo "%{F#6E6E6E}$volume_avg%{F-} $level%"
else;
    echo "%{F#6E6E6E}$volume_max%{F-} $level%"
fi
