#!/usr/bin/env zsh

source ~/.bin/utils.zsh

case "$1" in
    logout)
        if is_wayland; then
            swaymsg exit
        else
            i3-msg exit
        fi
        ;;
    update-shutdown | update-poweroff)
        updates update
        ;&
    shutdown | poweroff)
        systemctl poweroff
        ;;
    update-restart | update-reboot)
        updates update
        ;&
    restart | reboot)
        systemctl reboot
        ;;
    suspend)
        systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    selection)
        logout="logout"
        update_shutdown="update & shutdown"
        shutdown="shutdown"
        update_restart="update & restart/reboot"
        restart="restart/reboot"
        suspend="suspend"
        hibernate="hibernate"

        selection=$(echo -e "$logout\n$update_shutdown\n$shutdown\n$update_restart\n$restart\n$suspend\n$hibernate" | rofi -dmenu -i -window-title "actions")

        if [[ $selection = "$logout" ]]; then
            power-options logout
        elif [[ $selection = "$update_shutdown" ]]; then
            power-options update-shutdown
        elif [[ $selection = "$shutdown" ]]; then
            power-options shutdown
        elif [[ $selection = "$update_restart" ]]; then
            power-options update-restart
        elif [[ $selection = "$restart" ]]; then
            power-options restart
        elif [[ $selection = "$suspend" ]]; then
            power-options suspend
        elif [[ $selection = "$hibernate" ]]; then
            power-options hibernate
        fi
        ;;
    *)
        echo "Usage: $0 {suspend|hibernate|update-restart|restart|update-shutdown|shutdown|logout|selection}"
        exit 2
esac

exit 0
