#!/usr/bin/env zsh

set -

if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
    grim - | wl-copy
else
    maim -s | xclip -selection clipboard -t image/png

fi

notify-send -u low "Screenshot saved to clipboard!" --expire-time 5
