#!/usr/bin/env zsh

set -

if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
    url=`grim -g "$(slurp)" - | imgur.sh`
    echo -n "$url" | wl-copy
else

fi

echo "URL: $url"

notify-send -u low "Screenshot uploaded!" --expire-time 5
