#!/usr/bin/env zsh

set -

if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
    url=`grim -g "$(slurp)" - | imgur.sh`
else

fi


echo "URL: $url"

echo -n "$url" | wl-copy
notify-send -u low "Screenshot uploaded!" --expire-time 5
