#!/usr/bin/env zsh

amount=`yay -Pu | wc -l`

# Return as fast as possible, then update the repos and update.
echo "{\"text\": \"$amount\", \"alt\": \"default\"}"

amount=`yay -Syy > /dev/null; yay -Pu | wc -l`

echo "{\"text\": \"$amount\", \"alt\": \"default\"}"
