#!/usr/bin/env zsh

source ~/.bin/utils.zsh

if type "yay" > /dev/null; then
    amount=`yay -Qu | wc -l`
else
    amount=`dnf check-update --quiet --disablerepo="cpe-yum*" | wc -l`
fi

if is_wayland; then
    # Return as fast as possible, then update the repos and update.
    waybar-json "$amount" "There are $amount updates available, click to update."
    amount=`yay -Syy > /dev/null; yay -Qu | wc -l`
    waybar-json "$amount" "There are $amount updates available, click to update."
else
    polybar-output "$amount"
fi

