#!/usr/bin/env python3
from __future__ import annotations

import subprocess
import sys


def period_changed(old_period: str, new_period: str) -> None:
    """Redshift period-changed event hook.

    Possible periods: night, daytime, transition, none (only for old period).

    Args:
        old_period: str: The old period transitioning from.
        new_period: str: The new period transitioning to.
    """

    is_dark = new_period == "night" or (
        old_period == "daytime" and new_period == "transition"
    )
    gtk_theme = "Materia-dark" if is_dark else "Materia"
    subprocess.run(
        [
            "gsettings",
            "set",
            "org.gnome.desktop.interface",
            "gtk-theme",
            f'"{gtk_theme}"',
        ]
    )
    subprocess.run(
        [
            "gsettings",
            "set",
            "org.gnome.desktop.interface",
            "color-scheme",
            "prefer-dark" if is_dark else "prefer-light",
        ]
    )


if __name__ == "__main__":
    match sys.argv:
        case [_, "period-changed", old_period, new_period]:
            period_changed(old_period, new_period)
        case _:
            print("usage: darkmode period-changed <old_period> <new_period>")
            print()
            print("Possible periods: night, daytime, transition.")
